# Generated by Django 5.2.4 on 2025-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=300, verbose_name='Origin')),
                ('destination', models.CharField(max_length=300, verbose_name='Destination')),
                ('start_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Date Time')),
                ('end_date_time', models.DateTimeField(blank=True, null=True, verbose_name='End Date Time')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation_model',
                'ordering': ['start_date_time'],
            },
        ),
        migrations.CreateModel(
            name='TelephoneTaxiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300, verbose_name='Organization')),
                ('server_url', models.URLField(verbose_name='Server URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Telephone Taxi',
                'verbose_name_plural': 'Telephone Taxi',
                'db_table': 'telephone_taxi_model',
                'ordering': ['organization'],
            },
        ),
    ]
