# Generated by Django 5.2.4 on 2025-09-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0003_telephonetaximodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='end_date_time',
        ),
    ]
