# Generated by Django 5.2.4 on 2025-09-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0004_remove_reservationmodel_end_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmodel',
            options={'ordering': ['date_time'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='start_date_time',
            new_name='date_time',
        ),
    ]
