# Generated by Django 5.2.4 on 2025-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0005_alter_reservationmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='private key')),
                ('public_key', models.TextField(verbose_name='public key')),
                ('use_count', models.PositiveIntegerField(verbose_name='use count')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription_model',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Time'),
        ),
    ]
