# Generated by Django 5.2.7 on 2025-11-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0006_inscriptionmodel_alter_reservationmodel_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام غذا')),
                ('category', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('original_price', models.PositiveIntegerField(verbose_name='قیمت اصلی (تومان)')),
                ('final_price', models.PositiveIntegerField(verbose_name='قیمت نهایی (تومان)')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود است')),
                ('is_special', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم های منو',
                'db_table': 'menu_item',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=300, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید رستوران'), ('confirmed', 'تایید توسط رستوران'), ('preparing', 'در حال آماده سازی'), ('on_delivery', 'تحویل داده شده به پیک'), ('delivered', 'تحویل داده شده به مشتری توسط پیک'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='جمع کل (تومان)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 'order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد (تومان)')),
                ('subtotal', models.PositiveIntegerField(verbose_name='جمع (تومان)')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم های سفارش',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='رستوران بزرگمهر', max_length=300, verbose_name='نام رستوران')),
                ('server_url', models.URLField(verbose_name='آدرس سرور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن رستوران')),
                ('address', models.TextField(blank=True, verbose_name='آدرس رستوران')),
            ],
            options={
                'verbose_name': 'تنظیمات رستوران',
                'verbose_name_plural': 'تنظیمات رستوران',
                'db_table': 'restaurant_settings',
                'ordering': ['restaurant_name'],
            },
        ),
        migrations.DeleteModel(
            name='ReservationModel',
        ),
        migrations.DeleteModel(
            name='TelephoneTaxiModel',
        ),
        migrations.AlterModelOptions(
            name='inscriptionmodel',
            options={'ordering': ['id'], 'verbose_name': 'کلید رمزنگاری', 'verbose_name_plural': 'کلیدهای رمزنگاری'},
        ),
        migrations.AlterField(
            model_name='inscriptionmodel',
            name='private_key',
            field=models.TextField(verbose_name='کلید خصوصی'),
        ),
        migrations.AlterField(
            model_name='inscriptionmodel',
            name='public_key',
            field=models.TextField(verbose_name='کلید عمومی'),
        ),
        migrations.AlterField(
            model_name='inscriptionmodel',
            name='use_count',
            field=models.PositiveIntegerField(verbose_name='تعداد استفاده'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='menu_item_categor_ad4fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_special', 'is_available'], name='menu_item_is_spec_973f43_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date'], name='order_order_d_ed7c62_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone_number', '-order_date'], name='order_phone_n_f757c3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_35c31c_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reservation_Module.menuitem', verbose_name='آیتم منو'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Reservation_Module.order', verbose_name='سفارش'),
        ),
    ]
