# Generated by Django 5.2.8 on 2025-11-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0008_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=300, verbose_name='User Fullname')),
                ('origin', models.CharField(max_length=300, verbose_name='Origin')),
                ('destination', models.CharField(max_length=300, verbose_name='Destination')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservation_model',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='TelephoneTaxiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300, verbose_name='Organization')),
                ('server_url', models.URLField(verbose_name='Server URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Telephone Taxi',
                'verbose_name_plural': 'Telephone Taxi',
                'db_table': 'telephone_taxi_model',
                'ordering': ['organization'],
            },
        ),
    ]
