# Generated by Django 5.2.8 on 2025-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0009_reservationmodel_telephonetaximodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='destination',
            field=models.CharField(max_length=300, verbose_name='مقصد'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='origin',
            field=models.CharField(max_length=300, verbose_name='مبدا'),
        ),
    ]
