# Generated by Django 5.2.8 on 2025-11-11 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0010_alter_reservationmodel_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('to_source', 'در مسیر مبدا'), ('at_source', 'در مبدا'), ('to_destination', 'در مسیر مقصد'), ('at_destination', 'به مقصد رسید')], db_index=True, default='to_source', max_length=20, verbose_name='وضعیت تاکسی'),
        ),
        migrations.CreateModel(
            name='TaxiStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('to_source', 'در مسیر مبدا'), ('at_source', 'در مبدا'), ('to_destination', 'در مسیر مقصد'), ('at_destination', 'به مقصد رسید')], max_length=20, null=True, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(choices=[('to_source', 'در مسیر مبدا'), ('at_source', 'در مبدا'), ('to_destination', 'در مسیر مقصد'), ('at_destination', 'به مقصد رسید')], max_length=20, verbose_name='وضعیت جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('changed_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='تغییر دهنده')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='Reservation_Module.reservationmodel', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'لاگ وضعیت تاکسی',
                'verbose_name_plural': 'لاگ\u200cهای وضعیت تاکسی',
                'db_table': 'taxi_status_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
