# Generated by Django 5.2.4 on 2025-09-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='user_fullname',
            field=models.CharField(default='', max_length=300, verbose_name='User Fullname'),
            preserve_default=False,
        ),
    ]
