# Generated by Django 5.2.4 on 2025-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0002_reservationmodel_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephonetaximodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
