# Generated by Django 5.2.8 on 2025-11-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_Module', '0007_menuitem_order_orderitem_restaurantsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'db_table': 'customer',
                'ordering': ['-updated_at', 'name'],
                'indexes': [models.Index(fields=['phone_number'], name='customer_phone_n_d31982_idx'), models.Index(fields=['-updated_at'], name='customer_updated_b3907f_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Reservation_Module.customer', verbose_name='مشتری'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-order_date'], name='order_custome_ee6c6a_idx'),
        ),
    ]
